### ISSUE TITLE
Leanback (Google TV) enabled

### ISSUE THREAD

**Issue by Thorfinn66** [Lemkinator/GetIcon#2]
App works very well on Android TV when sideloading. 👍
Everything seems to be controllable with remote control. 

Only issues are:
1. It doesn't have leanback support and banner. So it doesn't show up on most launchers.
2. The highlight color when selecting icons is very faint and hard to see.

It would be a great enhancement to have it directly available in TV version of Google Play Store too.

**Comment by Lemkinator** [comment]
I'm not very experienced with Android TV, so any help would be greatly appreciated.

Regarding the 2. issue, could you please provide more details and include screenshots, if possible?

**Comment by Thorfinn66** [comment]
I don't think you have to do much as your app already works on tv. It's just a few changes in the manifest and adding a 320x180 banner icon. 

https://developer.android.com/training/tv/get-started/create

Google have been so "nice" and removed the screenshot option from Google TV. I can't even do it from adb anymore 😡

Best I can do is take a picture of TV using phone.

**Comment by Thorfinn66** [comment]
![PXL_20241010_123720598.jpg](https://github.com/user-attachments/assets/7f36d8ca-2794-4925-a731-8d5568da713b)

It's really hard to see, but the "Basic Web Browser" icon is highlighted with a faint pinkish background.

**Comment by Lemkinator** [comment]
Thank you, I will take a look at it when I have some free time.

**Comment by Lemkinator** [comment]
I checked the highlighting color on my phone and on an android tv emulator:
![geticon_phone_light](https://github.com/user-attachments/assets/b1011df1-30da-43ab-abc0-ac33e9ca5403)
![geticon_phone_dark](https://github.com/user-attachments/assets/d001d009-6f6e-40cc-aaca-1a6ac94a9d31)
![geticon_tv_light](https://github.com/user-attachments/assets/6644ec39-54bb-4fbe-8ffc-fe6cdc5fe01c)
![geticon_tv_dark](https://github.com/user-attachments/assets/efab3587-f727-444c-9418-c105dd080892)

I think this is fine. Idk why its hard to see on your tv, maybe check your tv settings (Contrast,...). Moreover, since this color is not directly defined by me, I dont really want to modify it. You can also try to use Dark Mode, contrast is a little bit better there imo...

**Comment by Thorfinn66** [comment]
Its a common "problem" with apps that are not build for TV ND have leanback support setup I'm manifest.
Then the select color is very faint (kinda make sense, as it's not useful in same way on touch devices)

And om android tv boxes, you can't do themes or adjust colors.
But thanks for looking into it. 👍

**Comment by Lemkinator** [comment]
There is no need to change your theme. There is an in-app option to set the app to Dark Mode. It is the first option on the settings screen.
Regarding contrast, this is not something you set on your Android TV box. Instead, you need to configure this in your display settings on your actual TV, not the box.

**Comment by Thorfinn66** [comment]
I know. But the brightness and contrast is set to correct values for viewing.

But dark mode is much better. 
No problems with seeing what is highlighted. 
I thought it was disabled at first.
But when I selected "System defaults", first, I could select the dark mode. 👍

**Comment by Lemkinator** [comment]
Good👍🏽
I am glad that was helpful.
Thank you for reporting the issue. I may consider changing this in the future.
